### ISSUE TITLE
Удаление временных файлов

### ISSUE THREAD

**Issue by kini24** [zxzharmlesszxz/eset_mirror_script#1]
В web-папке существует каталог tmp, где хранятся временные файлы. Со временем их накапливается очень много, так как эта папка никогда не чистится. Можно, конечно, чистить ее из cron'а, но, думаю, это будет немного некорректно. Можно ли добавить соответствующую функцию, которая будет выполнять очистку этой временной папки?

**Comment by zxzharmlesszxz** [comment]
Эти файлы там присутствуют только при включенном параметре
```
; Debuging update.ver files
; 0 - on
; 1 - off
debug_update = 0
```
и их автоматическая очистка как раз и не нужна
