### ISSUE TITLE
Зеркало для зеркала

### ISSUE THREAD

**Issue by kini24** [zxzharmlesszxz/eset_mirror_script#2]
Ваш скрипт у меня развернут на нескольких серверах. Попытался сделать следующее. На сервере А добавил в параметр mirror файла конфигурации адрес сервер В, затем попробовал обновить базы на сервере А. В итоге, в логе вижу строчку, что сервер В недоступен. При этом клиенты с сервера В обновляются нормально, сервер всегда доступен.
Возможно, я что-то не так сделал (или просто не сделал). Можно ли сделать так, чтобы Ваш скрипт, расположенный на сервере А, смог обновить свои базы с сервера В, базы на котором также были скачаны при помощи Вашего скрипта?

**Comment by zxzharmlesszxz** [comment]
Сделано
