### ISSUE TITLE
Валидация ключей

### ISSUE THREAD

**Issue by kini24** [zxzharmlesszxz/eset_mirror_script#3]
Здравствуйте!
Испытываю сейчас немного другую конфигурацию: apache 2.4 + php7-fpm. Запускаю скрипт update.php на поиск ключей. Поиск проходит нормально, но:
1. На некоторые ключи он показывает, что срок действия истек. Это нормально, я понимаю.
2. На некоторые ключи он не показывает срока действия, просто говорит, что он не прошел проверку валидности. С этим немного непонятно, но, допустим, что они заблокированы по каким-то причинам.
Наугад выбрал один такой ключ из списка "невалидных", вставил его в антивирус и запустил обновление. Процесс обнеовления пошел, то есть ключ был принят.
3. Открываю сайт trialeset.ru, генерирую ключ на 7 дней. Вставляю его в nod_keys.valid в соответствии с указанным здесь форматом. То есть беру заведомо рабочий ключ. Запускаю скрипт и получаю сообщение, что ключ недействителен. Почему?
Вставляю этот же ключ в антивирус на компьютере, указываю сервер обновлений "Выбирать автоматически". Обновление проходит нормально, файлы скачиваются. Смущает только, что версия базы после завершения обновления отличается от версии на другом сервере, на котором также используется Ваш скрипт. Например, антивирус показывает версию 17858, а сервер показывает 17859.

Включение log_level=5 и запуск debuging_update.php на консоль ничего не выводит

**Comment by zxzharmlesszxz** [comment]
Будет время - посмотрю что там с ключами. 
А так - все ключи проверяются на сервере eset, и что он отвечает именно на эти ключи я не знаю.

**Comment by kini24** [comment]
Возможно, я не прав. Мне кажется, что дело в том, что FastCGI, который сейчас используется на моем сервере, некорректно работает с заголовками авторизации и, соответственно, не отправляет логин/пароль на серверы обновлений

**Comment by kini24** [comment]
Загрузил скрипт заново с github, попробовал - все заработало. Хотя не так давно скачивал его и возникла вот такая непонятка с ключами
