### ISSUE TITLE
Не скачивает базы для 11-й версии

### ISSUE THREAD

**Issue by kini24** [zxzharmlesszxz/eset_mirror_script#4]
Несмотря на то, что в конфиге настроено скачивание всех баз, базы для 11-й версии антивируса не скачиваются. В логах строчки следующие:
_[ver. 11] Зеркало update.eset.com недоступно_
И так для всех серверов из списка. Можно это как-то побороть?
И просто заметка. В таблице вместо "Присутствуют языки" пишется "Пристуствуют языки". Заметил давно, но это не критично, поэтому не упоминал :-)

**Comment by zxzharmlesszxz** [comment]
На форуме https://forum.lissyara.su/soft-f3/shustryj-skript-skript-zerkala-nod32-t42296-s950.html где-то на страницах я уже писал что 11 версии бд НЕ СУЩЕСТВУЕТ!
11 версия обновляется с 10 бд. ( по крайней мере так было)
Если что-то поменялось - дай знать на форуме
