### ISSUE TITLE
Error in nginx conf

### ISSUE THREAD

**Issue by morfair** [zxzharmlesszxz/eset_mirror_script#5]
In nginx error log:

<code>
2018/12/04 14:23:07 [emerg] 16268#16268: pcre_compile() failed: unrecognized character after (? or (?- in "^(.*Update.*BPC\ (?\d+))" at "\d+))" in /etc/nginx/sites-enabled/eset:4
</code>

nginx version: nginx/1.10.3
Debian 9

**Comment by zxzharmlesszxz** [comment]
You need get code from raw Readme.md file, not from git-web or any ide
