### ISSUE TITLE
Notice: Undefined offset: 3 in eset_mirror_script/inc/classes/Nod32ms.class.php on line 308

### ISSUE THREAD

**Issue by xSoulRootx** [zxzharmlesszxz/eset_mirror_script#7]
Error on run:
php update.php
get many
Notice: Undefined offset: 3 in eset_mirror_script/inc/classes/Nod32ms.class.php on line 308
PHP Notice:  Undefined offset: 3 in eset_mirror_script/inc/classes/Nod32ms.class.php on line 308

**Comment by zxzharmlesszxz** [comment]
Hi!
How you setup script?
OS, php version, php modules, unrar?

**Comment by zxzharmlesszxz** [comment]
Your key file don't have right format "login:name:expire_date:version"
